// <auto-generated />
using System;
using CompetitionsTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompetitionsTest.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616141831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionsTest.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("CompetitionsTest.Models.CompetitionDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("DayNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("CompetitionDays");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.LinearScaleConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaxLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<string>("MinLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("LinearScaleConfigurations");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionDayId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionMark")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDayId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridAnswerKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GridConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("RowKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GridConfigurationId");

                    b.ToTable("GridAnswerKeys");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GridConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GridConfigurationId");

                    b.ToTable("GridColumns");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("GridConfigurations");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GridConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GridConfigurationId");

                    b.ToTable("GridRows");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.QuestionAnswerKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("QuestionAnswerKeys");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("CompetitionsTest.Models.CompetitionDay", b =>
                {
                    b.HasOne("CompetitionsTest.Models.Competition", "Competition")
                        .WithMany("Days")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.LinearScaleConfiguration", b =>
                {
                    b.HasOne("CompetitionsTest.Models.QuestionModel.Question", "Question")
                        .WithOne("LinearScaleConfiguration")
                        .HasForeignKey("CompetitionsTest.Models.QuestionModel.LinearScaleConfiguration", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.Question", b =>
                {
                    b.HasOne("CompetitionsTest.Models.CompetitionDay", "CompetitionDay")
                        .WithMany("Questions")
                        .HasForeignKey("CompetitionDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionDay");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridAnswerKey", b =>
                {
                    b.HasOne("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridConfiguration", "GridConfiguration")
                        .WithMany("AnswerKeys")
                        .HasForeignKey("GridConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridConfiguration");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridColumn", b =>
                {
                    b.HasOne("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridConfiguration", "GridConfiguration")
                        .WithMany("Columns")
                        .HasForeignKey("GridConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridConfiguration");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridConfiguration", b =>
                {
                    b.HasOne("CompetitionsTest.Models.QuestionModel.Question", "Question")
                        .WithOne("GridConfiguration")
                        .HasForeignKey("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridConfiguration", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridRow", b =>
                {
                    b.HasOne("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridConfiguration", "GridConfiguration")
                        .WithMany("Rows")
                        .HasForeignKey("GridConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridConfiguration");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.QuestionAnswerKey", b =>
                {
                    b.HasOne("CompetitionsTest.Models.QuestionModel.Question", "Question")
                        .WithOne("CorrectAnswer")
                        .HasForeignKey("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.QuestionAnswerKey", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.QuestionOption", b =>
                {
                    b.HasOne("CompetitionsTest.Models.QuestionModel.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CompetitionsTest.Models.Competition", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("CompetitionsTest.Models.CompetitionDay", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.Question", b =>
                {
                    b.Navigation("CorrectAnswer");

                    b.Navigation("GridConfiguration");

                    b.Navigation("LinearScaleConfiguration");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionModel.QuestionCongifuration.GridQuestion.GridConfiguration", b =>
                {
                    b.Navigation("AnswerKeys");

                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
