// <auto-generated />
using CompetitionsTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompetitionsTest.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611122151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionsTest.Models.CompetitionDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNum")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompetitionDays");
                });

            modelBuilder.Entity("CompetitionsTest.Models.LinearScaleConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaxLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<string>("MinLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("LinearScaleConfigurations");
                });

            modelBuilder.Entity("CompetitionsTest.Models.MultipleChoiceGridQuestion.GridColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GridConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GridConfigurationId");

                    b.ToTable("GridColumns");
                });

            modelBuilder.Entity("CompetitionsTest.Models.MultipleChoiceGridQuestion.GridRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GridConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GridConfigurationId");

                    b.ToTable("GridRows");
                });

            modelBuilder.Entity("CompetitionsTest.Models.MultipleChoiceGridQuestion.MultipleChoiceGridConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelectionMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("MultipleChoiceGridConfigurations");
                });

            modelBuilder.Entity("CompetitionsTest.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionDayId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDayId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("CompetitionsTest.Models.LinearScaleConfiguration", b =>
                {
                    b.HasOne("CompetitionsTest.Models.Question", "Question")
                        .WithOne("LinearScaleConfiguration")
                        .HasForeignKey("CompetitionsTest.Models.LinearScaleConfiguration", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CompetitionsTest.Models.MultipleChoiceGridQuestion.GridColumn", b =>
                {
                    b.HasOne("CompetitionsTest.Models.MultipleChoiceGridQuestion.MultipleChoiceGridConfiguration", "GridConfiguration")
                        .WithMany("Columns")
                        .HasForeignKey("GridConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridConfiguration");
                });

            modelBuilder.Entity("CompetitionsTest.Models.MultipleChoiceGridQuestion.GridRow", b =>
                {
                    b.HasOne("CompetitionsTest.Models.MultipleChoiceGridQuestion.MultipleChoiceGridConfiguration", "GridConfiguration")
                        .WithMany("Rows")
                        .HasForeignKey("GridConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridConfiguration");
                });

            modelBuilder.Entity("CompetitionsTest.Models.MultipleChoiceGridQuestion.MultipleChoiceGridConfiguration", b =>
                {
                    b.HasOne("CompetitionsTest.Models.Question", "Question")
                        .WithOne("MultipleChoiceGridConfiguration")
                        .HasForeignKey("CompetitionsTest.Models.MultipleChoiceGridQuestion.MultipleChoiceGridConfiguration", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CompetitionsTest.Models.Question", b =>
                {
                    b.HasOne("CompetitionsTest.Models.CompetitionDay", "CompetitionDay")
                        .WithMany("Questions")
                        .HasForeignKey("CompetitionDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionDay");
                });

            modelBuilder.Entity("CompetitionsTest.Models.QuestionOption", b =>
                {
                    b.HasOne("CompetitionsTest.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CompetitionsTest.Models.CompetitionDay", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CompetitionsTest.Models.MultipleChoiceGridQuestion.MultipleChoiceGridConfiguration", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("CompetitionsTest.Models.Question", b =>
                {
                    b.Navigation("LinearScaleConfiguration");

                    b.Navigation("MultipleChoiceGridConfiguration");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
